version: "3.8"

services:
  policy_match_web:
    image: codedevin/policy_match_web:v1.6
    build:
      context: .
    container_name: policy_match_web_container
    restart: always
    ports:
      - "0.0.0.0:3001:3000"
    environment:
      NEXT_PUBLIC_API_URL: https://www.deeplinkcn.com
